### ISSUE TITLE
Error: Could not initialize class org.jvnet.hudson.test.TestPluginManager

### ISSUE THREAD

**Issue by FreyLuis** [jenkinsci/jenkins-test-harness#566]
### Jenkins and plugins versions report

I'm getting the following error, when trying to initialize `JenkinsRule`:

```
java.lang.NoClassDefFoundError: Could not initialize class org.jvnet.hudson.test.TestPluginManager
	at org.jvnet.hudson.test.JenkinsRule.<init>(JenkinsRule.java:344)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at de.akdb.pers.ci.JobScriptsSpec.$spock_initializeSharedFields(JobScriptsSpec.groovy:16)
```

<details>
  <summary>Environment</summary>

Here are my Gradle dependencies:

  ```Gradle
ext {
    jobDslVersion = '1.81'
    jenkinsVersion = '2.375.3'
}

configurations {
    testPlugins {}
}

dependencies {
    implementation 'org.codehaus.groovy:groovy-all:2.4.17'
    implementation 'org.spockframework:spock-core:1.0-groovy-2.4'

    // Jenkins test harness dependencies
    testImplementation 'org.jenkins-ci.main:jenkins-test-harness:1949.vb_b_37feefe78c'
    testImplementation "org.jenkins-ci.main:jenkins-war:${jenkinsVersion}"

    // Job DSL plugin including plugin dependencies
    implementation "org.jenkins-ci.plugins:job-dsl-core:${jobDslVersion}"
    implementation "org.jenkins-ci.plugins:job-dsl:${jobDslVersion}@jar"
    testImplementation 'org.jenkins-ci.plugins:structs:1.20@jar'

    implementation 'org.xmlunit:xmlunit-core:2.5.1'

    testPlugins 'org.jenkins-ci.plugins:structs:1.20'
    testPlugins 'io.jenkins.plugins:warnings-ng:10.0.3'
}
  ```

</details>

I also got the same error with the version `jenkins-test-harness:2.56`. Also i found this stackoverflow question with the same problem: https://stackoverflow.com/questions/51724860/jenkins-job-failed-with-error-java-lang-noclassdeffounderror , sadly without an answer.

Here is my test, that initializes JenkinsRule:
```Groovy
package de.akdb.pers.ci

import groovy.io.FileType
import javaposse.jobdsl.dsl.DslScriptLoader
import javaposse.jobdsl.plugin.JenkinsJobManagement
import jenkins.model.Jenkins
import org.junit.ClassRule
import org.jvnet.hudson.test.JenkinsRule
import spock.lang.Shared
import spock.lang.Specification
import spock.lang.Unroll

class JobScriptsSpec extends Specification {
    @Shared
    @ClassRule
    JenkinsRule jenkinsRule = new JenkinsRule()

    @Unroll
    def 'test script #file.name'(File file) {
        given:
        def jobManagement = new JenkinsJobManagement(System.out, [:], new File('.'))

        when:
        new DslScriptLoader(jobManagement).runScript(file.text)

        then:
        noExceptionThrown()

        where:
        file << jobFiles
    }

    static List<File> getJobFiles() {
        List<File> files = []
        new File('jobs').eachFileRecurse {
            if (it.name.endsWith('.groovy')) {
                files << it
            }
        }
        files
    }
}
```

Am i doing something wrong? Is the JDK version I'm using a problem?

### What Operating System are you using (both controller, and any agents involved in the problem)?

OS: Windows Server 2019
JDK: Eclipse Adoptium jdk-17.0.3.7
Gradle: 8.0.2

### Reproduction steps

Initializing JenkinsRule

### Expected Results

works

### Actual Results

doesn't work

**Comment by basil** [comment]
Using Gradle for Jenkins plugin development is not officially supported by the Jenkins core development team.

For problems with https://github.com/jenkinsci/gradle-jpi-plugin, file an issue with its maintainers.

We strongly encourage you to use Maven and `maven-hpi-plugin` for Jenkins plugin development.
