### ISSUE TITLE
`DirectoryNotEmptyException` thrown by `TemporaryDirectoryAllocator#dispose` in `JenkinsRule#after` on Windows

### ISSUE THREAD

**Issue by strangelookingnerd** [jenkinsci/jenkins-test-harness#612]
### Jenkins and plugins versions report

Currently only happens on [ci.jenkins.io](https://ci.jenkins.io) and can not be reproduced on my local Windows machine.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows

### Reproduction steps

Have a JUnit5 test with `JenkinsRule` running a Job
Job directory is not being deleted properly in `JenkinsRule#after`

See [test code](https://github.com/jenkinsci/custom-folder-icon-plugin/blob/main/src/test/java/jenkins/plugins/foldericon/BuildStatusFolderIconTest.java#L162-L194)

See [failing test](https://ci.jenkins.io/job/Plugins/job/custom-folder-icon-plugin/job/main/lastCompletedBuild/testReport/jenkins.plugins.foldericon/BuildStatusFolderIconTest/windows_11___Build__windows_11____testRunningBuildStatusIcon_JenkinsRule_/)

### Expected Results

Job directory is being cleaned up *or* there is no exception thrown if it fails and the test succeeds.

### Actual Results

`DirectoryNotEmptyException` is thrown in `JenkinsRule#after` (causing an IOException with an empty exception message) and test fails

Stacktrace:
```
java.io.IOException: 
	at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:144)
	at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
	at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
	at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
	at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
	at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
	at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
	at org.jvnet.hudson.test.TemporaryDirectoryAllocator.dispose(TemporaryDirectoryAllocator.java:99)
	at org.jvnet.hudson.test.TestEnvironment.dispose(TestEnvironment.java:84)
	at org.jvnet.hudson.test.JenkinsRule.after(JenkinsRule.java:524)
	at org.jvnet.hudson.test.junit.jupiter.JenkinsExtension.afterEach(JenkinsExtension.java:26)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$12(TestMethodTestDescriptor.java:260)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:276)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:276)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:275)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:259)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:144)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.nio.file.DirectoryNotEmptyException: C:\Jenkins\workspace\s_custom-folder-icon-plugin_main\target\tmp\j h12616395869530307222\jobs\folder\jobs\Success\builds\2
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:271)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1181)
	at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:141)
	... 67 more
```

### Anything else?

Since this is not reliably reproducible and only happens on Windows I suspect something like a slow filesystem being the root cause. 
For some reason the message of the `IOException` that is thrown in my test is empty, even though it [should have the path in it](https://github.com/jenkinsci/jenkins-test-harness/blob/f258a61fc686369e784ac4a8916d2be50462d9fb/src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java#L96C30-L124). For me a strong indicator that the files were actually deleted but the filesystem was too slow.

However I personally do not see a reason why a test should fail because of this in the first place 🤔 
Comparing [TemporaryDirectoryAllocator#dispose and TemporaryDirectoryAllocator#disposeAsync](https://github.com/jenkinsci/jenkins-test-harness/blob/f258a61fc686369e784ac4a8916d2be50462d9fb/src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java#L96C30-L124) it shows to me that logging the `IOException` thrown is just fine.

Maybe use `java.io.File.deleteOnExit()` as a last remedy instead?

**Comment by slonopotamus** [comment]
> Maybe use `java.io.File.deleteOnExit()` as a last remedy instead?

The point of `TemporaryDirectoryAllocator` is _not_ to delete files. Nobody cares about them. Its goal is to detect leaked open file descriptors.

**Comment by strangelookingnerd** [comment]
Maybe I'm missing something, but `TemporaryDirectoryAllocator` does [delete files](https://github.com/jenkinsci/jenkins-test-harness/blob/f258a61fc686369e784ac4a8916d2be50462d9fb/src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java#LL141C37-L141C37). 
I see your point though. Maybe adding a retry loop would work around the problem?

**Comment by MarkEWaite** [comment]
I believe that the issue in this specific test is that the job that was started with `DelayBuilder()` has not completed in all cases when the test method exits.  I think that an additional call needs to be made after the final assertions to wait for the job to complete, then the test can exit.  A similar pattern was used in lockable resources plugin https://github.com/jenkinsci/lockable-resources-plugin/pull/519/files

Caveat: I've not run the tests in a debugger to confirm that is the case.  You're welcome to ignore my comments if I'm misunderstanding the purpose of `DelayBuilder()`

**Comment by strangelookingnerd** [comment]
@MarkEWaite That may actually be the root cause. I was still not able to reproduce it on my machine but I adapted my test to your suggestion anyways. Build seems fine so far but I'll keep an eye on it.

I still feel like there is something hidden here. How does the `IOException` thrown not have any message attached to it?
How can this even happen looking at the code of [TemporaryDirectoryAllocator#delete](https://github.com/jenkinsci/jenkins-test-harness/blob/f258a61fc686369e784ac4a8916d2be50462d9fb/src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java#L126C12-L147)
I still suspect a slow file system at fault here and would argue that it would be a good idea to compensate for that possibility in the implementation. Any thoughts?

**Comment by jglick** [comment]
> See [test code](https://github.com/jenkinsci/custom-folder-icon-plugin/blob/main/src/test/java/jenkins/plugins/foldericon/BuildStatusFolderIconTest.java#L162-L194)
> 
> See [failing test](https://ci.jenkins.io/job/Plugins/job/custom-folder-icon-plugin/job/main/lastCompletedBuild/testReport/jenkins.plugins.foldericon/BuildStatusFolderIconTest/windows_11___Build__windows_11____testRunningBuildStatusIcon_JenkinsRule_/)

Neither of these are permalinks—they point to the current trunk and the last build, respectively—so it is hard to recreate what they _were_ at the time you filed this issue.

At any rate, it looks like https://github.com/jenkinsci/custom-folder-icon-plugin/commit/c1c5d984f0d9eaf4b334610ab5dc7e7167ff05b0 should have fixed the test bug: leaving a build running (and potentially actively writing files in some background thread) past the end of the test.

> How does the `IOException` thrown not have any message attached to it?

https://github.com/jenkinsci/jenkins-test-harness/blob/41c9cb349299a89fa84ca4598df8636e6cb2ecb8/src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java#L144 suggests that there were no children left at the moment the exception was wrapped; probably some `…\jobs\folder\jobs\Success\builds\2\*` file was just being deleted by another thread around the same time.
